// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.12.4
// source: proto/image_resizer.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResizeImageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageData     []byte                 `protobuf:"bytes,1,opt,name=image_data,json=imageData,proto3" json:"image_data,omitempty"` // Raw image bytes
	Width         uint32                 `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`                         // Desired width
	Height        uint32                 `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`                       // Desired height
	Quality       uint32                 `protobuf:"varint,4,opt,name=quality,proto3" json:"quality,omitempty"`                     // JPEG quality (1-100)
	GpuId         uint32                 `protobuf:"varint,5,opt,name=gpu_id,json=gpuId,proto3" json:"gpu_id,omitempty"`            // Optional GPU ID for multi-GPU setups
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResizeImageRequest) Reset() {
	*x = ResizeImageRequest{}
	mi := &file_proto_image_resizer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResizeImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResizeImageRequest) ProtoMessage() {}

func (x *ResizeImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_image_resizer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResizeImageRequest.ProtoReflect.Descriptor instead.
func (*ResizeImageRequest) Descriptor() ([]byte, []int) {
	return file_proto_image_resizer_proto_rawDescGZIP(), []int{0}
}

func (x *ResizeImageRequest) GetImageData() []byte {
	if x != nil {
		return x.ImageData
	}
	return nil
}

func (x *ResizeImageRequest) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *ResizeImageRequest) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *ResizeImageRequest) GetQuality() uint32 {
	if x != nil {
		return x.Quality
	}
	return 0
}

func (x *ResizeImageRequest) GetGpuId() uint32 {
	if x != nil {
		return x.GpuId
	}
	return 0
}

type ResizeImageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResizedImage  []byte                 `protobuf:"bytes,1,opt,name=resized_image,json=resizedImage,proto3" json:"resized_image,omitempty"` // Resized image bytes
	UsedGpu       bool                   `protobuf:"varint,2,opt,name=used_gpu,json=usedGpu,proto3" json:"used_gpu,omitempty"`               // Indicates if GPU was used
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // Error message if applicable
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResizeImageResponse) Reset() {
	*x = ResizeImageResponse{}
	mi := &file_proto_image_resizer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResizeImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResizeImageResponse) ProtoMessage() {}

func (x *ResizeImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_image_resizer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResizeImageResponse.ProtoReflect.Descriptor instead.
func (*ResizeImageResponse) Descriptor() ([]byte, []int) {
	return file_proto_image_resizer_proto_rawDescGZIP(), []int{1}
}

func (x *ResizeImageResponse) GetResizedImage() []byte {
	if x != nil {
		return x.ResizedImage
	}
	return nil
}

func (x *ResizeImageResponse) GetUsedGpu() bool {
	if x != nil {
		return x.UsedGpu
	}
	return false
}

func (x *ResizeImageResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_proto_image_resizer_proto protoreflect.FileDescriptor

var file_proto_image_resizer_proto_rawDesc = string([]byte{
	0x0a, 0x19, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x72, 0x65,
	0x73, 0x69, 0x7a, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x92, 0x01, 0x0a, 0x12, 0x52, 0x65, 0x73, 0x69, 0x7a, 0x65, 0x49, 0x6d, 0x61,
	0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x6d, 0x61,
	0x67, 0x65, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x69,
	0x6d, 0x61, 0x67, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x77, 0x69, 0x64, 0x74,
	0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x12, 0x16,
	0x0a, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06,
	0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x71, 0x75, 0x61, 0x6c, 0x69, 0x74,
	0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x71, 0x75, 0x61, 0x6c, 0x69, 0x74, 0x79,
	0x12, 0x15, 0x0a, 0x06, 0x67, 0x70, 0x75, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x05, 0x67, 0x70, 0x75, 0x49, 0x64, 0x22, 0x7a, 0x0a, 0x13, 0x52, 0x65, 0x73, 0x69, 0x7a,
	0x65, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x23,
	0x0a, 0x0d, 0x72, 0x65, 0x73, 0x69, 0x7a, 0x65, 0x64, 0x5f, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0c, 0x72, 0x65, 0x73, 0x69, 0x7a, 0x65, 0x64, 0x49, 0x6d,
	0x61, 0x67, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x64, 0x5f, 0x67, 0x70, 0x75, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x75, 0x73, 0x65, 0x64, 0x47, 0x70, 0x75, 0x12, 0x23,
	0x0a, 0x0d, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x32, 0x54, 0x0a, 0x0c, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x69,
	0x7a, 0x65, 0x72, 0x12, 0x44, 0x0a, 0x0b, 0x52, 0x65, 0x73, 0x69, 0x7a, 0x65, 0x49, 0x6d, 0x61,
	0x67, 0x65, 0x12, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x73, 0x69, 0x7a,
	0x65, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x73, 0x69, 0x7a, 0x65, 0x49, 0x6d, 0x61, 0x67,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x2e, 0x5a, 0x2c, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6a, 0x65, 0x61, 0x75, 0x63, 0x68, 0x74, 0x65,
	0x72, 0x2f, 0x67, 0x6f, 0x2d, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x2d, 0x61, 0x64, 0x6a, 0x75, 0x73,
	0x74, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
})

var (
	file_proto_image_resizer_proto_rawDescOnce sync.Once
	file_proto_image_resizer_proto_rawDescData []byte
)

func file_proto_image_resizer_proto_rawDescGZIP() []byte {
	file_proto_image_resizer_proto_rawDescOnce.Do(func() {
		file_proto_image_resizer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_image_resizer_proto_rawDesc), len(file_proto_image_resizer_proto_rawDesc)))
	})
	return file_proto_image_resizer_proto_rawDescData
}

var file_proto_image_resizer_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_image_resizer_proto_goTypes = []any{
	(*ResizeImageRequest)(nil),  // 0: proto.ResizeImageRequest
	(*ResizeImageResponse)(nil), // 1: proto.ResizeImageResponse
}
var file_proto_image_resizer_proto_depIdxs = []int32{
	0, // 0: proto.ImageResizer.ResizeImage:input_type -> proto.ResizeImageRequest
	1, // 1: proto.ImageResizer.ResizeImage:output_type -> proto.ResizeImageResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_image_resizer_proto_init() }
func file_proto_image_resizer_proto_init() {
	if File_proto_image_resizer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_image_resizer_proto_rawDesc), len(file_proto_image_resizer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_image_resizer_proto_goTypes,
		DependencyIndexes: file_proto_image_resizer_proto_depIdxs,
		MessageInfos:      file_proto_image_resizer_proto_msgTypes,
	}.Build()
	File_proto_image_resizer_proto = out.File
	file_proto_image_resizer_proto_goTypes = nil
	file_proto_image_resizer_proto_depIdxs = nil
}
