// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: proto/image_resizer.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ImageResizer_ResizeImage_FullMethodName = "/proto.ImageResizer/ResizeImage"
)

// ImageResizerClient is the client API for ImageResizer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ImageResizerClient interface {
	ResizeImage(ctx context.Context, in *ResizeImageRequest, opts ...grpc.CallOption) (*ResizeImageResponse, error)
}

type imageResizerClient struct {
	cc grpc.ClientConnInterface
}

func NewImageResizerClient(cc grpc.ClientConnInterface) ImageResizerClient {
	return &imageResizerClient{cc}
}

func (c *imageResizerClient) ResizeImage(ctx context.Context, in *ResizeImageRequest, opts ...grpc.CallOption) (*ResizeImageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResizeImageResponse)
	err := c.cc.Invoke(ctx, ImageResizer_ResizeImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ImageResizerServer is the server API for ImageResizer service.
// All implementations must embed UnimplementedImageResizerServer
// for forward compatibility.
type ImageResizerServer interface {
	ResizeImage(context.Context, *ResizeImageRequest) (*ResizeImageResponse, error)
	mustEmbedUnimplementedImageResizerServer()
}

// UnimplementedImageResizerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedImageResizerServer struct{}

func (UnimplementedImageResizerServer) ResizeImage(context.Context, *ResizeImageRequest) (*ResizeImageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResizeImage not implemented")
}
func (UnimplementedImageResizerServer) mustEmbedUnimplementedImageResizerServer() {}
func (UnimplementedImageResizerServer) testEmbeddedByValue()                      {}

// UnsafeImageResizerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ImageResizerServer will
// result in compilation errors.
type UnsafeImageResizerServer interface {
	mustEmbedUnimplementedImageResizerServer()
}

func RegisterImageResizerServer(s grpc.ServiceRegistrar, srv ImageResizerServer) {
	// If the following call pancis, it indicates UnimplementedImageResizerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ImageResizer_ServiceDesc, srv)
}

func _ImageResizer_ResizeImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResizeImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImageResizerServer).ResizeImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImageResizer_ResizeImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImageResizerServer).ResizeImage(ctx, req.(*ResizeImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ImageResizer_ServiceDesc is the grpc.ServiceDesc for ImageResizer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ImageResizer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.ImageResizer",
	HandlerType: (*ImageResizerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ResizeImage",
			Handler:    _ImageResizer_ResizeImage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/image_resizer.proto",
}
